var tree= [
    {
        "name":"第一条染色体",
        "id":"",
        "type":"",
        "color":"",
        "value":"",
        "children":[
                {
                    "name":"第一段",
                    "id":"1",
                    "type":"2",
                    "color":"#B3DE69",
                    "value":"3",
                    "children":[
                        {
                            "name":"第一个基因",
                            "id":"1",
                            "type":"triangle",
                            "color":"#006699",
                            "value":"2",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"1",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"2",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FDB462",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"yellow",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"yellow",
                            "value":"",
                            "r":""//外接圆绘三角形
                        }
                    ]
                },
                {
                    "name":"第二段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"#B7704C",
                    "y":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        }
                    ]
                },
                {
                    "name":"第三段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第四段",
                    "id":"",
                    "type":"",
                    "color":"red",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第五段",
                    "id":"",
                    "type":"",
                    "color":"#FF3399",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第六段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                }
        ]
    },
    {
        "name":"第二条染色体",
        "id":"",
        "type":"",
        "color":"",
        "value":"",
        "children":[
                {
                    "name":"第一段",
                    "id":"1",
                    "type":"2",
                    "color":"#B3DE69",
                    "value":"3",
                    "children":[
                        {
                            "name":"第一个基因",
                            "id":"1",
                            "type":"triangle",
                            "color":"#006699",
                            "value":"2",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"1",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"2",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FDB462",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"yellow",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"yellow",
                            "value":"",
                            "r":""//外接圆绘三角形
                        }
                    ]
                },
                {
                    "name":"第二段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"#B7704C",
                    "y":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        }
                    ]
                },
                {
                    "name":"第三段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第四段",
                    "id":"",
                    "type":"",
                    "color":"red",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第五段",
                    "id":"",
                    "type":"",
                    "color":"#FF3399",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第六段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                }
        ]
    },
    {
        "name":"第二条染色体",
        "id":"",
        "type":"",
        "color":"",
        "value":"",
        "children":[
                {
                    "name":"第一段",
                    "id":"1",
                    "type":"2",
                    "color":"#B3DE69",
                    "value":"3",
                    "children":[
                        {
                            "name":"第一个基因",
                            "id":"1",
                            "type":"triangle",
                            "color":"#006699",
                            "value":"2",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"1",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"2",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FDB462",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"yellow",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"yellow",
                            "value":"",
                            "r":""//外接圆绘三角形
                        }
                    ]
                },
                {
                    "name":"第二段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"#B7704C",
                    "y":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        }
                    ]
                },
                {
                    "name":"第三段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第四段",
                    "id":"",
                    "type":"",
                    "color":"red",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第五段",
                    "id":"",
                    "type":"",
                    "color":"#FF3399",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第六段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                }
        ]
    },
    {
        "name":"第二条染色体",
        "id":"",
        "type":"",
        "color":"",
        "value":"",
        "children":[
                {
                    "name":"第一段",
                    "id":"1",
                    "type":"2",
                    "color":"#B3DE69",
                    "value":"3",
                    "children":[
                        {
                            "name":"第一个基因",
                            "id":"1",
                            "type":"triangle",
                            "color":"#006699",
                            "value":"2",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"1",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"2",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FDB462",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"yellow",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"yellow",
                            "value":"",
                            "r":""//外接圆绘三角形
                        }
                    ]
                },
                {
                    "name":"第二段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"#B7704C",
                    "y":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        }
                    ]
                },
                {
                    "name":"第三段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第四段",
                    "id":"",
                    "type":"",
                    "color":"red",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第五段",
                    "id":"",
                    "type":"",
                    "color":"#FF3399",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第六段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                }
        ]
    }
]