var tree= [
    {
        "name":"第一条染色体",
        "id":"",
        "type":"",
        "color":"",
        "value":"",
        "children":[
                {
                    "name":"第一段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"",
                    "children":[
                        {
                            "name":"第一个基因",
                            "id":"triangle",
                            "type":"",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"triangle",
                            "type":"",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"triangle",
                            "type":"",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
						{
                            "name":"第一个基因",
                            "id":"triangle",
                            "type":"",
                            "color":"yellow",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"yellow",
                            "value":"",
                            "r":""//外接圆绘三角形
                        }
                    ]
                },
                {
                    "name":"第二段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"",
                    "y":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"triangle",
                            "type":"",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第三段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第四段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第五段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"triangle",
                            "type":"",
                            "color":"red",
                            "value":"",
                            "r":""//外接圆绘三角形
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                }
        ]
    }
]