/**
 * 数据说明：
 * 所有数据都以json格式呈现，程序通过遍历json数据的形式绘制svg图像，格式如下
 * 必需填写的字段有第二层的color
 * 第三层的id,type,color,value,filter
 * type有两种类型：circle和triangle，分别绘制成圆形和三角形
 * color主要用于控制每个圆圈和三角形和左侧柱条每一段的颜色显示
 * id则预留了为以后与后端交互时的唯一编码
 * value为携带的数据
 * filter为条件过滤时的分类
 * 
 */
var tree= [
    {
        "name":"第一条染色体",
        "id":"",
        "type":"",
        "color":"",
        "value":"",
        "children":[
                {
                    "name":"第一段",
                    "id":"1",
                    "type":"2",
                    "color":"#B3DE69",
                    "value":"3",
                    "children":[
                        {
                            "name":"第一个基因",
                            "id":"1",
                            "type":"triangle",
                            "color":"#006699",
                            "value":"2",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"1",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"2",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FDB462",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"yellow",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"yellow",
                            "value":"",
                            "filter":"1" 
                        }
                    ]
                },
                {
                    "name":"第二段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"#B7704C",
                    "y":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        }
                    ]
                },
                {
                    "name":"第三段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第四段",
                    "id":"",
                    "type":"",
                    "color":"red",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第五段",
                    "id":"",
                    "type":"",
                    "color":"#FF3399",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第六段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                }
        ]
    },
    {
        "name":"第二条染色体",
        "id":"",
        "type":"",
        "color":"",
        "value":"",
        "children":[
                {
                    "name":"第一段",
                    "id":"1",
                    "type":"2",
                    "color":"#B3DE69",
                    "value":"3",
                    "children":[
                        {
                            "name":"第一个基因",
                            "id":"1",
                            "type":"triangle",
                            "color":"#006699",
                            "value":"2",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"1",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"2",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FDB462",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"yellow",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"yellow",
                            "value":"",
                            "filter":"1" 
                        }
                    ]
                },
                {
                    "name":"第二段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"#B7704C",
                    "y":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":""
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":""
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"3" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"3" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"2"                    
                        }
                    ]
                },
                {
                    "name":"第三段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第四段",
                    "id":"",
                    "type":"",
                    "color":"red",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第五段",
                    "id":"",
                    "type":"",
                    "color":"#FF3399",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第六段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                }
        ]
    },
    {
        "name":"第二条染色体",
        "id":"",
        "type":"",
        "color":"",
        "value":"",
        "children":[
                {
                    "name":"第一段",
                    "id":"1",
                    "type":"2",
                    "color":"#B3DE69",
                    "value":"3",
                    "children":[
                        {
                            "name":"第一个基因",
                            "id":"1",
                            "type":"triangle",
                            "color":"#006699",
                            "value":"2",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"1",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"2",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FDB462",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"yellow",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"yellow",
                            "value":"",
                            "filter":"1" 
                        }
                    ]
                },
                {
                    "name":"第二段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"#B7704C",
                    "y":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        }
                    ]
                },
                {
                    "name":"第三段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第四段",
                    "id":"",
                    "type":"",
                    "color":"red",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第五段",
                    "id":"",
                    "type":"",
                    "color":"#FF3399",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第六段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                }
        ]
    },
    {
        "name":"第二条染色体",
        "id":"",
        "type":"",
        "color":"",
        "value":"",
        "children":[
                {
                    "name":"第一段",
                    "id":"1",
                    "type":"2",
                    "color":"#B3DE69",
                    "value":"3",
                    "children":[
                        {
                            "name":"第一个基因",
                            "id":"1",
                            "type":"triangle",
                            "color":"#006699",
                            "value":"2",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"1",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"2",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FDB462",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"yellow",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"yellow",
                            "value":"",
                            "filter":"1" 
                        }
                    ]
                },
                {
                    "name":"第二段",
                    "id":"",
                    "type":"",
                    "color":"",
                    "value":"#B7704C",
                    "y":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        }
                    ]
                },
                {
                    "name":"第三段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第四段",
                    "id":"",
                    "type":"",
                    "color":"red",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第五段",
                    "id":"",
                    "type":"",
                    "color":"#FF3399",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                },
                {
                    "name":"第六段",
                    "id":"",
                    "type":"",
                    "color":"#B7704C",
                    "value":"",
                    "children":[
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"circle",
                            "color":"red",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B7704C",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#FB8072",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#BC80BD",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#FF3399",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#80B1D3",
                            "value":"",
                            "filter":"1" 
                        },
						{
                            "name":"第一个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"#BEBADA",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"#B3DE69",
                            "value":"",
                            "filter":"1" 
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"circle",
                            "color":"blue",
                            "value":"",
                            "r":"10"
                        },
                        {
                            "name":"第二个基因",
                            "id":"",
                            "type":"triangle",
                            "color":"green",
                            "value":"",
                            "r":"10"
                        }
                    ]
                }
        ]
    }
]